-- Campaign: tpch-sspq-fk-r1-20260730
-- Apply only after the SSOT schema preflight reports that all eight constraints
-- and their exact definitions are absent.

ALTER TABLE NATION
  ADD CONSTRAINT fk_nation_region
  FOREIGN KEY (N_REGIONKEY) REFERENCES REGION (R_REGIONKEY);

ALTER TABLE SUPPLIER
  ADD CONSTRAINT fk_supplier_nation
  FOREIGN KEY (S_NATIONKEY) REFERENCES NATION (N_NATIONKEY);

ALTER TABLE CUSTOMER
  ADD CONSTRAINT fk_customer_nation
  FOREIGN KEY (C_NATIONKEY) REFERENCES NATION (N_NATIONKEY);

ALTER TABLE PARTSUPP
  ADD CONSTRAINT fk_partsupp_supplier
  FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER (S_SUPPKEY);

ALTER TABLE PARTSUPP
  ADD CONSTRAINT fk_partsupp_part
  FOREIGN KEY (PS_PARTKEY) REFERENCES PART (P_PARTKEY);

ALTER TABLE ORDERS
  ADD CONSTRAINT fk_orders_customer
  FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER (C_CUSTKEY);

ALTER TABLE LINEITEM
  ADD CONSTRAINT fk_lineitem_orders
  FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS (O_ORDERKEY);

ALTER TABLE LINEITEM
  ADD CONSTRAINT fk_lineitem_partsupp
  FOREIGN KEY (L_PARTKEY, L_SUPPKEY)
  REFERENCES PARTSUPP (PS_PARTKEY, PS_SUPPKEY);

